# Generated by Django 6.0.2 on 2026-02-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name des Schiffs', max_length=100, unique=True)),
                ('capacity', models.IntegerField(help_text='Ladekapazität in Tonnen')),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('in_voyage', 'Auf Fahrt'), ('maintenance', 'Wartung')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schiff',
                'verbose_name_plural': 'Schiffe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_port', models.CharField(max_length=100, verbose_name='Starthafen')),
                ('destination_port', models.CharField(max_length=100, verbose_name='Zielhafen')),
                ('start_date', models.DateTimeField(verbose_name='Startdatum')),
                ('end_date', models.DateTimeField(verbose_name='Enddatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to='logistics.ship', verbose_name='Schiff')),
            ],
            options={
                'verbose_name': 'Fahrt',
                'verbose_name_plural': 'Fahrten',
                'ordering': ['start_date'],
            },
        ),
    ]
